terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "7.20.0"
    }
  }
}

provider "google" {
  credentials = file(var.credentials)
  project     = var.project_id
  region      = var.region
}

resource "google_storage_bucket" "calls-bucket" {
  name          = var.gcs_bucket_name # this has to be unique across all of GCP
  location      = var.location
  force_destroy = true
  storage_class = var.gs_storage_class

  lifecycle_rule {
    condition {
      age = 1
    }
    action {
      type = "AbortIncompleteMultipartUpload"
    }
  }
}

resource "google_bigquery_dataset" "terraform-demo-dataset" {
  dataset_id = var.bq_dataset_name
  location   = var.location
}

resource "google_bigquery_dataset" "terraform-demo-dataset-demo" {
  dataset_id = var.bq_dataset_name_demo
  location   = var.location
}

# for data engineering zoomcamp
resource "google_bigquery_table" "table-test-yellow" {
  dataset_id          = var.bq_dataset_name_demo
  table_id            = "yellow_tripdata"
  deletion_protection = false

  time_partitioning {
    type  = "DAY"
    field = "tpep_pickup_datetime"
  }

  schema = <<EOF
[
  {
    "name": "unique_row_id",
    "type": "BYTES",
    "mode": "NULLABLE",
    "description": "A unique identifier for the trip, generated by hashing key trip attributes."
  },
  {
    "name": "filename",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "The source filename from which the trip data was loaded."
  },
  {
    "name": "VendorID",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc."
  },
  {
    "name": "tpep_pickup_datetime",
    "type": "TIMESTAMP",
    "mode": "NULLABLE",
    "description": "The date and time when the meter was engaged."
  },
  {
    "name": "tpep_dropoff_datetime",
    "type": "TIMESTAMP",
    "mode": "NULLABLE",
    "description": "The date and time when the meter was disengaged."
  },
  {
    "name": "passenger_count",
    "type": "INTEGER",
    "mode": "NULLABLE",
    "description": "The number of passengers in the vehicle. This is a driver-entered value."
  },
  {
    "name": "trip_distance",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "The elapsed trip distance in miles reported by the taximeter."
  },
  {
    "name": "RatecodeID",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride"
  },
  {
    "name": "store_and_fwd_flag",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "This flag indicates whether the trip record was held in vehicle memory before sending to the vendor. TRUE = store and forward trip, FALSE = not a store and forward trip"
  },
  {
    "name": "PULocationID",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "TLC Taxi Zone in which the taximeter was engaged."
  },
  {
    "name": "DOLocationID",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "TLC Taxi Zone in which the taximeter was disengaged."
  },
  {
    "name": "payment_type",
    "type": "INTEGER",
    "mode": "NULLABLE",
    "description": "A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip"
  },
  {
    "name": "fare_amount",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "The time-and-distance fare calculated by the meter."
  },
  {
    "name": "extra",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges."
  },
  {
    "name": "mta_tax",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "$0.50 MTA tax that is automatically triggered based on the metered rate in use."
  },
  {
    "name": "tip_amount",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "Tip amount. This field is automatically populated for credit card tips. Cash tips are not included."
  },
  {
    "name": "tolls_amount",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "Total amount of all tolls paid in trip."
  },
  {
    "name": "improvement_surcharge",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "$0.30 improvement surcharge assessed on hailed trips at the flag drop."
  },
  {
    "name": "total_amount",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "The total amount charged to passengers. Does not include cash tips."
  },
  {
    "name": "congestion_surcharge",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "Congestion surcharge applied to trips in congested zones."
  }
]
EOF
} 

resource "google_bigquery_table" "table-test-green" {
  dataset_id          = var.bq_dataset_name_demo
  table_id            = "green_tripdata"
  deletion_protection = false

  time_partitioning {
    type  = "DAY"
    field = "lpep_pickup_datetime"
  }

  schema = <<EOF
[
  {
    "name": "unique_row_id",
    "type": "BYTES",
    "mode": "NULLABLE",
    "description": "A unique identifier for the trip, generated by hashing key trip attributes."
  },
  {
    "name": "filename",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "The source filename from which the trip data was loaded."
  },
  {
    "name": "VendorID",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc."
  },
  {
    "name": "lpep_pickup_datetime",
    "type": "TIMESTAMP",
    "mode": "NULLABLE",
    "description": "The date and time when the meter was engaged."
  },
  {
    "name": "lpep_dropoff_datetime",
    "type": "TIMESTAMP",
    "mode": "NULLABLE",
    "description": "The date and time when the meter was disengaged."
  },
  {
    "name": "store_and_fwd_flag",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "This flag indicates whether the trip record was held in vehicle memory before sending to the vendor. Y= store and forward trip N= not a store and forward trip"
  },
  {
    "name": "RatecodeID",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride"
  },
  {
    "name": "PULocationID",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "TLC Taxi Zone in which the taximeter was engaged."
  },
  {
    "name": "DOLocationID",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "TLC Taxi Zone in which the taximeter was disengaged."
  },
  {
    "name": "passenger_count",
    "type": "INTEGER",
    "mode": "NULLABLE",
    "description": "The number of passengers in the vehicle. This is a driver-entered value."
  },
  {
    "name": "trip_distance",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "The elapsed trip distance in miles reported by the taximeter."
  },
  {
    "name": "fare_amount",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "The time-and-distance fare calculated by the meter."
  },
  {
    "name": "extra",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges."
  },
  {
    "name": "mta_tax",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "$0.50 MTA tax that is automatically triggered based on the metered rate in use."
  },
  {
    "name": "tip_amount",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "Tip amount. This field is automatically populated for credit card tips. Cash tips are not included."
  },
  {
    "name": "tolls_amount",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "Total amount of all tolls paid in trip."
  },
  {
    "name": "ehail_fee",
    "type": "NUMERIC",
    "mode": "NULLABLE"
  },
  {
    "name": "improvement_surcharge",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "$0.30 improvement surcharge assessed on hailed trips at the flag drop."
  },
  {
    "name": "total_amount",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "The total amount charged to passengers. Does not include cash tips."
  },
  {
    "name": "payment_type",
    "type": "INTEGER",
    "mode": "NULLABLE",
    "description": "A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip"
  },
  {
    "name": "trip_type",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "A code indicating whether the trip was a street-hail or a dispatch. 1= Street-hail 2= Dispatch"
  },
  {
    "name": "congestion_surcharge",
    "type": "NUMERIC",
    "mode": "NULLABLE",
    "description": "Congestion surcharge applied to trips in congested zones."
  }
]
EOF

}