version: 2

seeds:
  - name: lookup_table
    config:
      column_types:
        codigo: string
  - name: problematica_problema
    config:
      column_types:
        codigo_problema: string
  - name: codigo_orientador
    config:
      column_types:
        id: string
        codigo_orientador: string
        nombre_orientador: string 