version: 2

sources:
  - name: raw_data
    description: "Raw data sources for llamatel calls"
    database: singular-arbor-401018 #google cloud project id
    schema: raw #dataset
    tables:
      - name: llamatel-llamadas 